// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC12pXFBncliSZQKbBrGDV0ocxYpIFCK0A',
    appId: '1:369938283854:web:090f958f98685b17bdb21f',
    messagingSenderId: '369938283854',
    projectId: 'sudheer-kondamuri',
    authDomain: 'sudheer-kondamuri.firebaseapp.com',
    storageBucket: 'sudheer-kondamuri.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcBdct_RqZCCzIDCnL6tgIuS3HswxuDD0',
    appId: '1:369938283854:android:6717bfab94737e6abdb21f',
    messagingSenderId: '369938283854',
    projectId: 'sudheer-kondamuri',
    storageBucket: 'sudheer-kondamuri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbUrVTiou8kVTW47Rkozh12MaCJEl5Jz4',
    appId: '1:369938283854:ios:ee2abc371de6cd02bdb21f',
    messagingSenderId: '369938283854',
    projectId: 'sudheer-kondamuri',
    storageBucket: 'sudheer-kondamuri.firebasestorage.app',
    iosBundleId: 'com.example.portifolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbUrVTiou8kVTW47Rkozh12MaCJEl5Jz4',
    appId: '1:369938283854:ios:ee2abc371de6cd02bdb21f',
    messagingSenderId: '369938283854',
    projectId: 'sudheer-kondamuri',
    storageBucket: 'sudheer-kondamuri.firebasestorage.app',
    iosBundleId: 'com.example.portifolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC12pXFBncliSZQKbBrGDV0ocxYpIFCK0A',
    appId: '1:369938283854:web:90b43960f08c9895bdb21f',
    messagingSenderId: '369938283854',
    projectId: 'sudheer-kondamuri',
    authDomain: 'sudheer-kondamuri.firebaseapp.com',
    storageBucket: 'sudheer-kondamuri.firebasestorage.app',
  );
}
